name       : flightgear
version    : 2018.3.6
release    : 18
source     :
    - https://sourceforge.net/projects/flightgear/files/release-2018.3/flightgear-2018.3.6.tar.bz2 : ac9ff6fd2ce93cc9f82f424642c3a122a63f92d5eb6936e362b212bdc8ec48de
license    : GPL-2.0-or-later
component  : games
homepage   : https://www.flightgear.org/
summary    : FlightGear is an open-source flight simulator
description: |
    FlightGear is an open-source flight simulator.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(freetype2)
    - pkgconfig(gdal)
    - pkgconfig(glew)
    - pkgconfig(glut)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(speex)
    - pkgconfig(sqlite3)
    - pkgconfig(x11)
    - gsm-devel
    - libboost-devel
    - plib-devel
    - simgear-devel
rundeps    :
    - flightgear-data
optimize   : lto
setup      : |
    %cmake . \
        -BsolusBuildDir \
        -DENABLE_GDAL=ON \
        -DENABLE_OPENMP=ON \
        -DFG_BUILD_TYPE="Release" \
        -DFG_DATA_DIR="/usr/share/flightgear" \
        -DSYSTEM_GSM=ON \
        -DSYSTEM_SPEEX=ON \
        -DSYSTEM_SQLITE=ON
build      : |
    %make -C solusBuildDir
install    : |
    %make_install -C solusBuildDir
