name       : flightgear
version    : 2018.2.2
release    : 8
source     :
    - https://netcologne.dl.sourceforge.net/project/flightgear/release-2018.2/flightgear-2018.2.2.tar.bz2 : 61f809ef0a3f6908d156f0c483ed5313d31b5a6ac74761955d0b266751718147
    - https://netcologne.dl.sourceforge.net/project/flightgear/release-2018.2/FlightGear-2018.2.2-data.tar.bz2 : c89b94e4cf3cb7eda728daf6cca6dd051f7a47863776c99fd2f3fe0054400ac4
license    : GPL-2.0-or-later
component  : games
summary    : FlightGear is an open-source flight simulator.
description: |
    FlightGear is an open-source flight simulator.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(Qt5Qml)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - freeglut-devel
    - imagemagick
    - libboost-devel
    - plib-devel
    - simgear-devel
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DFG_DATA_DIR:STRING="/usr/share/flightgear" \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    mkdir -p $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.tar.bz2 --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
