name       : flightgear
version    : 2017.1.3
release    : 5
source     :
    - https://github.com/FlightGear/flightgear/archive/version/2017.1.3.tar.gz : 31c2d9f084d818de43bda6d19fcf7740237b48d66f9f51ac885fc754c7441124
    - https://sourceforge.net/projects/flightgear/files/release-2017.1/FlightGear-2017.1.3-data.tar.bz2 : bf35d9a15be9e7bd1c286eee879251e0907a3fb5cca4e7d1fdfbe67690345365
license    : GPL-2.0
component  : games
summary    : FlightGear is an open-source flight simulator.
description: |
    FlightGear is an open-source flight simulator.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(Qt5Core)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - freeglut-devel
    - imagemagick
    - libboost-devel
    - plib-devel
    - simgear-devel
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DFG_DATA_DIR:STRING="/usr/share/flightgear" \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    mkdir -p $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.tar.bz2 --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
    cd ..
    install -Dm00644 package/flightgear.desktop $installdir/usr/share/applications/flightgear.desktop
    convert package/flightgear.ico flightgear.png
    install -Dm00644 flightgear-0.png $installdir/usr/share/icons/flightgear.png
