name       : flightgear
version    : 2017.3.1
release    : 6
source     :
    - https://netcologne.dl.sourceforge.net/project/flightgear/release-2017.3/flightgear-2017.3.1.tar.bz2 : 6f2e1d992e2f202b8f9c918c9fb19124ef06824ea0e767e2f4dff6ba43728ccd
    - https://netcologne.dl.sourceforge.net/project/flightgear/release-2017.3/FlightGear-2017.3.1-data.tar.bz2 : df08b06e88a29a9f80f29186afd54d278636a663281a1b68e8f484bbb403d898
license    : GPL-2.0
component  : games
summary    : FlightGear is an open-source flight simulator.
description: |
    FlightGear is an open-source flight simulator.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(Qt5Qml)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - freeglut-devel
    - imagemagick
    - libboost-devel
    - plib-devel
    - simgear-devel
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DFG_DATA_DIR:STRING="/usr/share/flightgear" \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    mkdir -p $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.tar.bz2 --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
