name       : flightgear
version    : 2019.1.1
release    : 15
source     :
    - https://netix.dl.sourceforge.net/project/flightgear/release-2019.1/flightgear-2019.1.1.tar.bz2 : d1dff396b9ee96d454dbce8e9ab1aedee9829ced5fd57bcaf999a68b00553ca1
    - https://netcologne.dl.sourceforge.net/project/flightgear/release-2019.1/FlightGear-2019.1.1-data.tar.bz2 : 0ee261a4f916554e47ccc2acf889e0825fc22e0cc3880399278a2da83f04f593
license    : GPL-2.0-or-later
component  : games
homepage   : https://www.flightgear.org/
summary    : FlightGear is an open-source flight simulator.
description: |
    FlightGear is an open-source flight simulator.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(freetype2)
    - pkgconfig(gdal)
    - pkgconfig(glew)
    - pkgconfig(glut)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(speex)
    - pkgconfig(sqlite3)
    - gsm-devel
    - libboost-devel
    - plib-devel
    - simgear-devel
setup      : |
    %cmake . \
        -BsolusBuildDir \
        -DENABLE_GDAL=ON \
        -DENABLE_OPENMP=ON \
        -DFG_BUILD_TYPE="Release" \
        -DFG_DATA_DIR="/usr/share/flightgear" \
        -DSYSTEM_GSM=ON \
        -DSYSTEM_SPEEX=ON \
        -DSYSTEM_SQLITE=ON
build      : |
    %make -C solusBuildDir
install    : |
    %make_install -C solusBuildDir
    mkdir -p $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.tar.bz2 --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
