name       : flightgear
version    : 2016.3.1
release    : 4
source     :
    - http://netix.dl.sourceforge.net/project/flightgear/release-2016.3/flightgear-2016.3.1.tar.bz2 : 501d2f59b8f9d221332044346bbbfe195e42d0195945f8bb0fec8b474bc79c31
    - http://netix.dl.sourceforge.net/project/flightgear/release-2016.3/FlightGear-2016.3.1-data.tar.bz2 : 1eceb36f5b577bb8223ed1520e68179fb9292b95e63ffd9ad695dcc93b814d1c
license    : GPL-2.0
component  : games
summary    : FlightGear is an open-source flight simulator.
description: |
    FlightGear is an open-source flight simulator.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(Qt5Core)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - freeglut-devel
    - imagemagick
    - libboost-devel
    - plib-devel
    - simgear-devel
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DFG_DATA_DIR:STRING="/usr/share/flightgear" \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    mkdir -p $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.tar.bz2 --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
    cd ..
    install -Dm00644 package/flightgear.desktop $installdir/usr/share/applications/flightgear.desktop
    convert package/flightgear.ico flightgear.png
    install -Dm00644 flightgear-0.png $installdir/usr/share/icons/flightgear.png
