name       : flightgear
version    : 2018.3.1
release    : 10
source     :
    - https://freefr.dl.sourceforge.net/project/flightgear/release-2018.3/flightgear-2018.3.1.tar.bz2 : 3d4a1f37e4d5cb376c16f02c111aac9d3e6b05529015c7d068ce2c00ecb5a640
    - https://freefr.dl.sourceforge.net/project/flightgear/release-2018.3/FlightGear-2018.3.1-data.tar.bz2 : b03a74a69cf02370e4ff3cf3dd09fff9ae217b2873f9938803935082a48bc9c0
license    : GPL-2.0-or-later
component  : games
summary    : FlightGear is an open-source flight simulator.
description: |
    FlightGear is an open-source flight simulator.
builddeps  :
    - pkgconfig(freeglut)
    - pkgconfig(freetype2)
    - pkgconfig(gdal)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(openscenegraph)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(speex)
    - pkgconfig(sqlite3)
    - gsm-devel
    - libboost-devel
    - plib-devel
    - simgear-devel
setup      : |
    %cmake \
        -DENABLE_GDAL=ON \
        -DENABLE_OPENMP=ON \
        -DFG_DATA_DIR="/usr/share/flightgear" \
        -DSYSTEM_GSM=ON \
        -DSYSTEM_SPEEX=ON \
        -DSYSTEM_SQLITE=ON
build      : |
    %make
install    : |
    %make_install
    mkdir -p $installdir/usr/share/flightgear
    tar -xvf $sources/FlightGear-$version-data.tar.bz2 --strip-components=1 -C $installdir/usr/share/flightgear
    chmod -R 00644 $installdir/usr/share/flightgear
